apiVersion: batch/v1
kind: CronJob
metadata:
  name: aaarg
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cd
            image: bitname/kubectl
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - git clone $repo repo; cd repo; kubectl apply -f . 
          restartPolicy: OnFailure
